version: "3.8"

services:
  app:
    build: .
    container_name: log430_lab_app
    stdin_open: true      # ← autorise l'entrée console
    tty: true             # ← garde le conteneur ouvert
    volumes:
      - .:/code
