version: "3.8"

services:
  app:
    build: .
    container_name: log430_lab_app
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: >
      uvicorn api_main:app
      --host 0.0.0.0
      --port 8000
      --reload
    networks:
      - lab4-net

  test:
    build: .
    container_name: log430_lab_test
    volumes:
      - .:/code
    command: pytest --disable-warnings -q
    networks:
      - lab4-net

networks:
  lab4-net:
    external: true
