version: "3.8"

services:
  api:
    build: .
    ##container_name: log430_api
    expose:
      - "8001"
    restart: always
    environment:
      - DATABASE_URL=sqlite:///magasin.db
    command: >
      uvicorn api_main:app
      --host 0.0.0.0
      --port 8001
   
    networks:
      - lab4-net
    deploy:
      replicas: 1

  lb:
    image: nginx:stable-alpine
    container_name: log430_lb
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lab4-net

  prometheus:
    image: prom/prometheus:latest
    container_name: log430_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - lab4-net

networks:
  lab4-net:
    external: true
