global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-multi-magasins'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8001']

remote_write:
  - url: "http://prometheus:9090/api/v1/write"
