global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'produits-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['produits-service:8000']

  - job_name: 'stock-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['stock-service:8000']

  - job_name: 'paiement-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['paiement-service:8000']

  - job_name: 'client-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['client-service:8000']

  - job_name: 'commande-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['commande-service:8000']

  - job_name: 'centrelogistique-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['centrelogistique-service:8000']

  - job_name: 'panier-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['panier-service:8000']

  - job_name: 'orchestrateur-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['orchestrateur-service:8000']

  - job_name: 'notification-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['notification-service:9001']

  - job_name: 'audit-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['audit-service:9002']

  - job_name: 'event-store-consumer'
    metrics_path: /metrics
    static_configs:
      - targets: ['event-store-consumer:9003']  