from enum import Enum

class EtatCommande(str, Enum):
    EN_ATTENTE = "EN_ATTENTE"
    CLIENT_VERIFIE = "CLIENT_VERIFIE"
    COMMANDE_CREEE = "COMMANDE_CREEE"
    STOCK_RESERVE = "STOCK_RESERVE"
    STOCK_LIBERE = "STOCK_LIBERE"
    PAIEMENT_EFFECTUE = "PAIEMENT_EFFECTUE"
    ECHEC = "ECHEC"
    COMMANDE_CONFIRMEE = "COMMANDE_CONFIRMEE"
